import { useEffect, useState } from "react";
import DashboardLayout from "../../components/layouts/DashboardLayout";
import axiosInstance from "../../utils/axiosInstance";
import { API_PATHS } from "../../utils/apiPaths";
import { initials } from "../../utils/helper";

const ManageUsers = () => { const [users, setUsers] = useState([]); const download = () => axiosInstance.get(API_PATHS.reports.users, { responseType: "blob" }).then((res) => { const url = URL.createObjectURL(res.data); const link = document.createElement("a"); link.href = url; link.download = "users_report.xlsx"; link.click(); URL.revokeObjectURL(url); }); useEffect(() => { axiosInstance.get(API_PATHS.users).then((res) => setUsers(res.data)).catch(() => {}); }, []); return <DashboardLayout><div className="flex items-center justify-between"><h1 className="text-3xl font-bold">Team Members</h1><button onClick={download} className="rounded-xl border border-lime-300 bg-lime-50 px-5 py-3 text-sm font-bold text-lime-800">Download Report</button></div><div className="mt-7 grid gap-5 md:grid-cols-2 2xl:grid-cols-3">{users.map((user) => <article key={user._id} className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div className="flex items-center gap-4"><div className="grid h-12 w-12 place-items-center rounded-full bg-blue-600 font-bold text-white">{user.profileImageUrl ? <img src={user.profileImageUrl} className="h-full w-full rounded-full object-cover" /> : initials(user.name)}</div><div><h2 className="font-semibold">{user.name}</h2><p className="text-sm text-slate-500">{user.email}</p></div></div><div className="mt-5 grid grid-cols-3 text-center text-sm"><Count label="Pending" value={user.pendingTasks} color="text-violet-600" /><Count label="In Progress" value={user.inProgressTasks} color="text-cyan-600" /><Count label="Completed" value={user.completedTasks} color="text-lime-600" /></div></article>)}</div>{!users.length && <p className="py-16 text-center text-slate-400">No members found.</p>}</DashboardLayout>; };
const Count = ({ label, value = 0, color }) => <div><b className={color}>{value}</b><p className="mt-1 text-xs text-slate-500">{label}</p></div>;
export default ManageUsers;
