import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import toast from "react-hot-toast";
import DashboardLayout from "../../components/layouts/DashboardLayout";
import axiosInstance from "../../utils/axiosInstance";
import { API_PATHS } from "../../utils/apiPaths";
import { formatDate, priorityClass, statusClass } from "../../utils/helper";

const ViewTaskDetails = () => { const { id } = useParams(); const [task, setTask] = useState(null); useEffect(() => { axiosInstance.get(`${API_PATHS.tasks}/${id}`).then((res) => setTask(res.data)).catch(() => toast.error("Unable to load task")); }, [id]); const toggle = async (index) => { const todoChecklist = task.todoChecklist.map((item, i) => i === index ? { ...item, completed: !item.completed } : item); try { const { data } = await axiosInstance.put(`${API_PATHS.tasks}/${id}/todo`, { todoChecklist }); setTask(data.task); } catch { toast.error("Unable to update checklist"); } }; if (!task) return <DashboardLayout><p className="py-20 text-center text-slate-400">Loading task…</p></DashboardLayout>; return <DashboardLayout><article className="rounded-2xl border border-slate-100 bg-white p-7 shadow-sm"><div className="flex flex-wrap justify-between gap-4"><h1 className="text-3xl font-bold">{task.title}</h1><span className={`h-fit rounded-md px-3 py-1 text-sm font-semibold ${statusClass(task.status)}`}>{task.status}</span></div><h2 className="mt-7 text-sm font-medium text-slate-500">Description</h2><p className="mt-2 max-w-4xl leading-7 text-slate-700">{task.description || "No description provided."}</p><div className="mt-8 grid gap-6 sm:grid-cols-3"><Info label="Priority" value={<span className={`rounded-md px-3 py-1 text-sm font-semibold ${priorityClass(task.priority)}`}>{task.priority}</span>} /><Info label="Due Date" value={formatDate(task.dueDate)} /><Info label="Assigned To" value={task.assignedTo?.map((user) => user.name).join(", ") || "Unassigned"} /></div><h2 className="mt-9 text-lg font-bold">TODO Checklist</h2><div className="mt-4 space-y-3">{task.todoChecklist?.map((item, index) => <label key={item._id || index} className="flex cursor-pointer items-center gap-3 rounded-xl bg-slate-50 px-4 py-3"><input type="checkbox" checked={item.completed} onChange={() => toggle(index)} className="h-5 w-5 accent-blue-600" /><span className={item.completed ? "text-slate-400 line-through" : ""}>{item.text}</span></label>)}</div>{task.attachments?.length > 0 && <><h2 className="mt-9 text-lg font-bold">Attachments</h2><div className="mt-3 space-y-2">{task.attachments.map((link, index) => <a key={link} href={link} target="_blank" rel="noreferrer" className="block rounded-lg bg-slate-50 px-4 py-3 text-blue-600">{String(index + 1).padStart(2, "0")} &nbsp; {link}</a>)}</div></>}</article></DashboardLayout>; };
const Info = ({ label, value }) => <div><p className="text-sm text-slate-400">{label}</p><div className="mt-2 font-semibold">{value}</div></div>;
export default ViewTaskDetails;
