import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import { HiOutlineArrowUpTray } from "react-icons/hi2";
import AuthLayout from "../../components/layouts/AuthLayout";
import { TextInput } from "../../components/inputs/Inputs";
import axiosInstance from "../../utils/axiosInstance";
import { API_PATHS } from "../../utils/apiPaths";
import uploadImage from "../../utils/uploadImage";

const Signup = () => { const [form, setForm] = useState({ name: "", email: "", password: "", adminInviteToken: "", profileImageUrl: "" }); const [loading, setLoading] = useState(false); const [progress, setProgress] = useState(0); const navigate = useNavigate();
  const chooseImage = async (event) => { const file = event.target.files?.[0]; if (!file) return; try { setProgress(1); const url = await uploadImage(file, (e) => setProgress(Math.round((e.loaded * 100) / e.total))); setForm((value) => ({ ...value, profileImageUrl: url })); toast.success("Profile image uploaded"); } catch { toast.error("Image upload failed"); setProgress(0); } };
  const submit = async (event) => { event.preventDefault(); setLoading(true); try { const { data } = await axiosInstance.post(API_PATHS.auth.register, form); localStorage.setItem("token", data.token); localStorage.setItem("user", JSON.stringify(data)); toast.success("Account created"); navigate(data.role === "admin" ? "/admin/dashboard" : "/user/dashboard"); } catch (error) { toast.error(error.response?.data?.message || "Unable to create account"); } finally { setLoading(false); } };
  return <AuthLayout><h1 className="text-3xl font-bold">Create an Account</h1><p className="mt-2 text-slate-500">Join us today by entering your details below.</p><form onSubmit={submit} className="mt-7"><label className="mx-auto mb-6 flex h-20 w-20 cursor-pointer items-center justify-center overflow-hidden rounded-full bg-blue-50 text-blue-600"><input type="file" accept="image/png,image/jpeg" className="hidden" onChange={chooseImage} />{form.profileImageUrl ? <img src={form.profileImageUrl} className="h-full w-full object-cover" /> : <HiOutlineArrowUpTray className="text-3xl" />}</label>{progress > 0 && progress < 100 && <p className="mb-3 text-center text-xs text-blue-600">Uploading {progress}%</p>}<div className="grid gap-5 sm:grid-cols-2"><TextInput label="Full Name" placeholder="John" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><TextInput label="Email Address" type="email" placeholder="john@example.com" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><TextInput label="Password" type="password" minLength="8" placeholder="Min 8 Characters" required value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><TextInput label="Admin Invite Token" placeholder="6 Digit Code" value={form.adminInviteToken} onChange={(e) => setForm({ ...form, adminInviteToken: e.target.value })} /></div><button disabled={loading} className="mt-6 w-full rounded-xl bg-blue-600 py-3.5 text-sm font-bold text-white shadow-lg shadow-blue-200 disabled:opacity-60">{loading ? "CREATING..." : "SIGN UP"}</button></form><p className="mt-6 text-sm">Already have an account? <Link className="font-semibold text-blue-600" to="/login">Login</Link></p></AuthLayout>; };
export default Signup;
